id: IBFB4E024
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T08:23:21+00:00'
last_modified: '2022-06-08T05:06:58.380919+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4268
  title: རྨ་གཡང་ཕྱུག་མོའི་བཞད་སྒྲ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '9117':
      image_group_id: I1KG4995
      title: ''
      total_pages: 188
      order: 1
      base_file: 9117.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
