id: P005587
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4268
  title: རྨ་གཡང་ཕྱུག་མོའི་བཞད་སྒྲ
  author: ''
  volumes:
    aece2829ca3a4c93bac0169a46dd4d49:
      image_group_id: I1KG4995
      title: ''
      volume_number: 1
      total_pages: 188
      base_file: v001.txt
